
name: DEV

on:
  workflow_call:
    inputs:
      environment:
        description: "deploy to"
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, world! from DEV"

      - name: Checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - name: Get changes
        run: |
          set -x
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > locations.txt

          filenames=$(cat locations.txt)

          echo "#######################################################"
          echo "$filenames"
          echo "#######################################################"

          for file in $filenames
          do
            if [[ "$file" = *.py ]] && [[ -f $file ]]
            then
              echo "file is /$file"
            else
              echo "file is either not compatible or not available"
            fi
          done