
name: DEV

on:
  workflow_call:
    inputs:
      environment:
        description: "deploy to"
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "Hello, world! from DEV"

      - name: Checkout
        uses: actions/checkout@v3
        with:
           fetch-depth: 0
      - name: Get changes
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.event.after }} > locations.txt

          filenames=$(cat locations.txt)

          echo "#######################################################"
          echo "$filenames"
          echo "#######################################################"

          # for file in $filenames
          # do
          #   if [[ "$file" = *.py ]] && [[ -f $file ]]
          #   then
          #     echo "file is /$file"
          #   else
          #     echo "file is either not Python or not available"
          #   fi

          #   if [[ "$file" = *.html ]] && [[ -f $file ]]
          #   then
          #     echo "file is /$file"
          #   else
          #     echo "file is either not html or not available"
          #   fi

          #   if [[ "$file" = *.scala ]] && [[ -f $file ]]
          #   then
          #     echo "file is /$file"
          #   else
          #     echo "file is either not scala or not available"
          #   fi

          #   if [[ "$file" = *.r ]] && [[ -f $file ]]
          #   then
          #     echo "file is /$file"
          #   else
          #     echo "file is either not .r or not available"
          #   fi

          #   if [[ "$file" = *.sql ]] && [[ -f $file ]]
          #   then
          #     echo "file is /$file"
          #   else
          #     echo "file is either not sql or not available"
          #   fi
          # done

          for file in $filenames
          do
            case $file in
            "*.py")
            echo $file is a Python file
            ;;
            "*.html")
            echo $file is a html file
            ;;
            "*.sql")
            echo $file is a sql file
            ;;
          done